server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #是否从EurekaServer中抓取自己的信息，默认为true。单节点无所谓，集群时候必须开启才能结合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己注册到Euerka中
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

