server:
  port: 4433

spring:
  application:
    name: cloud-config-center

  cloud:
    config:
      server:
        git: #用github作为外部配置存储
          uri: https://github.com/TianLuhua/SpringcloudConfig.git   #git 项目的仓库地址
          search-paths:
          - config  #项目目录
      label: master #读取分支

#增加RabbitMQ支持
  rabbitmq:
    host: 47.99.109.141
    port: 5672
    username: tianluhua
    password: 123456

#rabbitMq 相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    #是否从EurekaServer中抓取自己的信息，默认为true。单节点无所谓，集群时候必须开启才能结合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己注册到Euerka中
    register-with-eureka: true
    service-url:
      #defaultZone: http://http://eureka7001.com:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

