server:
  port: 9527


spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-8001 # 名称可以随便取，但是要唯一
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，就是说满足改条件才会进行路由转发。 **表示匹配后面的任意字符

        - id: payment-8002
          uri: http://localhost:8002
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    #是否从EurekaServer中抓取自己的信息，默认为true。单节点无所谓，集群时候必须开启才能结合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己注册到Euerka中
    register-with-eureka: true
    service-url:
      #defaultZone: http://http://eureka7001.com:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
