server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service

eureka:
  client:
    #是否从EurekaServer中抓取自己的信息，默认为true。单节点无所谓，集群时候必须开启才能结合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己注册到Euerka中
    register-with-eureka: false
    service-url:
      #defaultZone: http://http://eureka7001.com:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

ribbon:
  ReadTimeout: 5000 #设置超时时间为5秒，默认为1秒
  ConnectTimeout: 5000

#配置OpenFeign日志级别
logging:
  level:
    com.tlh.springcloud.service.IPaymentService: debug
