server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      #nacos注册中心地址（nacos集群地址）
      discovery:
        server-addr: localhost:1111
      #nacos注册配置中心地址（nacos集群地址）
      config:
        server-addr: localhost:1111
        #指定配置文件类型
        file-extension: yaml

    sentinel:
      transport:
        # 配置Sentinel dashboard 地址
        dashboard: localhost:8080
        # 配置Sentinel端口，默认8719。如果被占用会自动从8719往上+1，直至找到没有被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'